name: Notify Server On Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Notify deploy server
        run: |
          curl -X POST http://103.161.97.193:3035/deploy/notify \
            -H "Content-Type: application/json" \
            -d '{
              "repo": "'"${{ github.repository }}"'",
              "branch": "'"${{ github.ref_name }}"'",
              "commit": "'"${{ github.sha }}"'",
              "author": "'"${{ github.actor }}"'",
              "message": "'"${{ github.event.head_commit.message }}"'"
            }'
